version: '3'

services:
  api:
    build: .
    container_name: classconnect-api
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8080}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    restart: always