version: '3'

services:
  api:
    build: .
    container_name: classconnect-api
    ports:
      - "${PORT:-6969}:${PORT:-6969}"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-6969}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    restart: always